# Generated by Django 4.1.7 on 2023-04-03 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflowBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('history', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowBase.state')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowBase.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
