# Generated by Django 4.1.7 on 2023-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowBase', '0003_workflow_is_deploy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
