# Generated by Django 4.1.4 on 2023-04-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workflowBase", "0006_transition_event_transition_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transition",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitionPermission",
                to="auth.group",
            ),
        ),
    ]
