# Generated by Django 4.1.4 on 2023-04-14 07:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workflowBase", "0008_alter_transition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="transitionevents",
            name="name",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("Mail", "Mail"), ("SMS", "SMS")], max_length=20
            ),
        ),
    ]
