# Generated by Django 4.1.4 on 2023-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflowBase", "0009_alter_state_name_alter_transitionevents_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transition",
            name="event",
        ),
        migrations.AlterField(
            model_name="transitionevents",
            name="name",
            field=models.CharField(
                choices=[("Mail", "Mail"), ("SMS", "SMS")], max_length=20
            ),
        ),
        migrations.AddField(
            model_name="transition",
            name="event",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="transitionEvent",
                to="workflowBase.transitionevents",
            ),
        ),
    ]
