# Generated by Django 4.1.4 on 2023-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflowBase",
            "0010_remove_transition_event_alter_transitionevents_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transition",
            name="event",
            field=models.ManyToManyField(
                blank=True, null=True, to="workflowBase.transitionevents"
            ),
        ),
    ]
