# Generated by Django 4.1.4 on 2023-05-15 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflowBase",
            "0012_alter_transition_event_remove_transition_permission_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflowBase.workflowinstance",
                    ),
                ),
                (
                    "end_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_state",
                        to="workflowBase.state",
                    ),
                ),
                (
                    "start_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_state",
                        to="workflowBase.state",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflowBase.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition History",
                "verbose_name_plural": "Transition Historys",
            },
        ),
    ]
